name: fuzz

on:
  push:
    branches: ['fuzz-ci', 'fuzz']

jobs:
  fuzzing:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        name: install fuzzer
        with:
          command: install
          args: cargo-fuzz
      - uses: actions-rs/cargo@v1
        name: run fuzzer
        with:
          command: fuzz
          args: run --release streams --jobs=1 -- -max_total_time=400 -rss_limit_mb=8192

