name: CI

on:
  push:
    branches: ['master', '0.5.x', 'fuzz-workspace-ci']
  pull_request:
  schedule:
    - cron: "21 3 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta]
        # exclude:
        #   - os: macos-latest
        #     rust: beta
        #   - os: windows-latest
        #     rust: beta

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --workspace --all-targets
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --workspace

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      # - uses: actions-rs/cargo@v1
        # with:
          # command: fmt
          # args: --all -- --check
      - uses: actions-rs/cargo@v1
        if: always()
        with:
          command: clippy
          args: --workspace --exclude fuzz --all-targets -- -D warnings
      - name: cd to fuzz workspace
        run: |
          cd fuzz
          echo "hello"
          echo `pwd`
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: where are you
        run: |
          echo "where are u"
          echo `pwd`
